SELECT CCk.CODE_COMBINATION_ID,
        CCK.CONCATENATED_SEGMENTS,
        CCK.SEGMENT1, (SELECT DESCRIPTION FROM FND_FLEX_VALUES_VL V WHERE FLEX_VALUE = CCK.SEGMENT1 AND FLEX_VALUE_SET_ID = '1014877') DESC1,
        CCK.SEGMENT2, (SELECT DESCRIPTION FROM FND_FLEX_VALUES_VL V WHERE FLEX_VALUE = CCK.SEGMENT2 AND FLEX_VALUE_SET_ID = '1014878') DESC2,
        CCK.SEGMENT3, (SELECT DESCRIPTION FROM FND_FLEX_VALUES_VL V WHERE FLEX_VALUE = CCK.SEGMENT3 AND FLEX_VALUE_SET_ID = '1014879') DESC3,
        CCK.SEGMENT4, (SELECT DESCRIPTION FROM FND_FLEX_VALUES_VL V WHERE FLEX_VALUE = CCK.SEGMENT4 AND FLEX_VALUE_SET_ID = '1014880') DESC4,
        CCK.SEGMENT5, (SELECT DESCRIPTION FROM FND_FLEX_VALUES_VL V WHERE FLEX_VALUE = CCK.SEGMENT5 AND FLEX_VALUE_SET_ID = '1014881') DESC5,
        CCK.SEGMENT6, (SELECT DESCRIPTION FROM FND_FLEX_VALUES_VL V WHERE FLEX_VALUE = CCK.SEGMENT6 AND FLEX_VALUE_SET_ID = '1014882') DESC6,
        CCK.SEGMENT7, (SELECT DESCRIPTION FROM FND_FLEX_VALUES_VL V WHERE FLEX_VALUE = CCK.SEGMENT7 AND FLEX_VALUE_SET_ID = '1014878') DESC7,
        CCK.SEGMENT8, (SELECT DESCRIPTION FROM FND_FLEX_VALUES_VL V WHERE FLEX_VALUE = CCK.SEGMENT8 AND FLEX_VALUE_SET_ID = '1014883') DESC8                           
FROM GL_CODE_COMBINATIONS_KFV CCK