SELECT AA.PRODUK,AA.NAME, SUM(AA.ORDERED_QUANTITY), SUM(AA.SHIPPED_QUANTITY),
 YNP_GET_TTL_PRODUKSIITEM((
                            SELECT organization_id FROM ORG_ORGANIZATION_DEFINITIONS WHERE operating_unit = AA.ORG_ID AND ORGANIZATION_CODE LIKE '%P' AND ROWNUM = 1
                            ), AA.produk,:TGL1,:TGL2) AS ttl_produksi,
YNP_GET_KAPASITAS(AA.ORG_ID,AA.produk,'1') as kapasitas_perhari,
last_day(TRUNC(TO_DATE (:TGL2, '/RRRR/MM/DD HH24:MI:SS'))) - TRUNC(TO_DATE (:TGL1,'RRRR/MM/DD HH24:MI:SS')) as TTL_HARI,
       YNP_GET_KAPASITAS(AA.ORG_ID,AA.produk, last_day(TRUNC(TO_DATE (:TGL2, '/RRRR/MM/DD HH24:MI:SS'))) - TRUNC(TO_DATE (:TGL1,'RRRR/MM/DD HH24:MI:SS'))) as TTL_kapasitas               
FROM
(
SELECT  A.ORG_ID,
        HAOU.NAME,
        A.ORDERED_DATE,
        A.ORDER_NUMBER,
        B.LINE_NUMBER,
        OTTT.NAME ORDER_TYPE,
        micv.segment1 produk,
        CASE
            WHEN D.ACCOUNT_NAME IS NULL OR D.ACCOUNT_NAME =''  THEN
                 d.attribute1
            ELSE D.ACCOUNT_NAME
        END CUSTOMER,
        MSI.SEGMENT1||'-'||MSI.SEGMENT2||'-'||MSI.SEGMENT3||'-'||MSI.SEGMENT4||'-'||MSI.SEGMENT5 ITEM_CODE,
        MSI.DESCRIPTION,
        B.ORDERED_QUANTITY,
        B.SHIPPED_QUANTITY
FROM OE_ORDER_HEADERS_ALL A,
        OE_ORDER_LINES_ALL B,
        hz_cust_accounts d,
        MTL_SYSTEM_ITEMS MSI,
        OE_TRANSACTION_TYPES_TL OTTT,
        HR_ALL_ORGANIZATION_UNITS HAOU,
        mtl_item_categories_v micv
WHERE A.HEADER_ID = B.HEADER_ID
AND d.cust_account_id =  A.SOLD_TO_ORG_ID
AND b.INVENTORY_ITEM_ID = msi.INVENTORY_ITEM_ID
AND msi.ORGANIZATION_ID = 89
AND OTTT.TRANSACTION_TYPE_ID = A.ORDER_TYPE_ID
AND A.ORG_ID = HAOU.ORGANIZATION_ID
AND b.INVENTORY_ITEM_ID = micv.INVENTORY_ITEM_ID
AND micv.organization_id = 89
AND micv.CATEGORY_SET_NAME LIKE 'NP Sales Class Category'
AND B.SHIPPING_INTERFACED_FLAG = 'Y'
AND MICV.SEGMENT1 NOT IN('RAW MATERIAL', 'SPAREPART', 'DEFAULT', 'REJECT', 'RPET')
AND A.ORDERED_DATE BETWEEN TRUNC(TO_DATE(:TGL1, 'RRRR/MM/DD HH24:MI:SS')) AND TRUNC(TO_DATE(:TGL2, 'RRRR/MM/DD HH24:MI:SS')+1)
ORDER BY NAME,PRODUK, ORDERED_DATE
) AA
GROUP BY  AA.PRODUK, AA.NAME, AA.ORG_ID
ORDER BY  AA.PRODUK, AA.NAME