SELECT DISTINCT PP.OU, REPLACE(PP.ITEMS, '%') AS ITEMS, (SELECT to_char(sysdate, 'YYYY') FROM DUAL),
       (SELECT YNP_RATIO_RETUR1('01', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_1_JAN,
       (SELECT YNP_RATIO_RETUR2('01', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_2_JAN,
       
       (SELECT YNP_RATIO_RETUR1('02', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_1_FEB,
       (SELECT YNP_RATIO_RETUR2('02', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_2_FEB,
       
       (SELECT YNP_RATIO_RETUR1('03', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_1_MAR,
       (SELECT YNP_RATIO_RETUR2('03', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_2_MAR,
       
       (SELECT YNP_RATIO_RETUR1('04', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_1_APR,
       (SELECT YNP_RATIO_RETUR2('04', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_2_APR,
       
       (SELECT YNP_RATIO_RETUR1('05', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_1_MAY,
       (SELECT YNP_RATIO_RETUR2('05', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_2_MAY,
       
       (SELECT YNP_RATIO_RETUR1('06', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_1_JUN,
       (SELECT YNP_RATIO_RETUR2('06', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_2_JUN,
       
       (SELECT YNP_RATIO_RETUR1('07', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_1_JUL,
       (SELECT YNP_RATIO_RETUR2('07', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_2_JUL,
       
       (SELECT YNP_RATIO_RETUR1('08', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_1_AUG,
       (SELECT YNP_RATIO_RETUR2('08', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_2_AUG,
       
       (SELECT YNP_RATIO_RETUR1('09', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_1_SEP,
       (SELECT YNP_RATIO_RETUR2('09', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_2_SEP,
       
       (SELECT YNP_RATIO_RETUR1('10', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_1_OCT,
       (SELECT YNP_RATIO_RETUR2('10', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_2_OCT,
       
       (SELECT YNP_RATIO_RETUR1('11', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_1_NOV,
       (SELECT YNP_RATIO_RETUR2('11', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_2_NOV,
       
       (SELECT YNP_RATIO_RETUR1('12', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_1_DEC,
       (SELECT YNP_RATIO_RETUR2('12', (SELECT to_char(sysdate, 'YYYY') FROM DUAL), PP.ITEMS, PP.OU) FROM DUAL) AS RETURN_2_DEC
FROM
(
SELECT DISTINCT A.ORGANIZATION_ID, A.SEGMENT1 || '-' || A.SEGMENT2 || '%' AS ITEMS,
       (SELECT CC.NAME
        FROM   HR_ALL_ORGANIZATION_UNITS CC,  HR_LOCATIONS_ALL DD
        WHERE  CC.LOCATION_ID = DD.LOCATION_ID
        AND    CC.ORGANIZATION_ID = (
                                     SELECT OPERATING_UNIT
                                     FROM   ORG_ORGANIZATION_DEFINITIONS
                                     WHERE  ORGANIZATION_ID = A.ORGANIZATION_ID
                                    )
       ) AS OU
FROM   MTL_SYSTEM_ITEMS_B A
WHERE  A.SEGMENT1 = 'FGP'
)PP
WHERE PP.OU IS NOT NULL
AND   PP.OU NOT LIKE '%Kreasi%'
AND   PP.OU NOT LIKE '%Pratama%'
ORDER BY PP.OU ASC


