/* Formatted on 2015/10/11 06:12 (Formatter Plus v4.8.8) */
SELECT mtrl.line_id line_id, mtrh.request_number request_number,
       mtrh.move_order_type move_order_type,
       mfg2.meaning move_order_type_name, mtrh.description description,
       mtrl.header_id header_id,
       mtt.transaction_source_type_id transaction_source_type_id,
       mtrl.transaction_type_id transaction_type_id,
       mtt.transaction_type_name transaction_type_name,
       mtt.transaction_action_id transaction_action_id,
       mtrl.line_number line_number, mtrl.organization_id organization_id,
       mtrl.inventory_item_id inventory_item_id, mtrl.revision revision,
       mtrl.from_subinventory_id from_subinventory_id,
       mtrl.from_subinventory_code from_subinventory_code,
       mss.locator_type from_sub_locator_type,
       mss.asset_inventory from_sub_asset,
       mss.quantity_tracked from_sub_quantity_tracked,
       mss.material_account from_sub_material_account,
       mtrl.from_locator_id from_locator_id,
       mtrl.to_subinventory_code to_subinventory_code,
       mss1.locator_type to_sub_locator_type,
       mss1.asset_inventory to_sub_asset,
       mss1.quantity_tracked to_sub_quantity_tracked,
       mss1.material_account to_sub_material_account,
       mtrl.to_subinventory_id to_subinventory_id,
       mtrl.to_locator_id to_locator_id, mtrl.to_account_id to_account_id,
       mtrl.ship_to_location_id ship_to_location_id,
       mtrl.lot_number lot_number,
       mtrl.serial_number_start serial_number_start,
       mtrl.serial_number_end serial_number_end, mtrl.uom_code uom_code,
       mtrl.quantity quantity, mtrl.required_quantity required_quantity,
       mtrl.quantity_delivered quantity_delivered,
       mtrl.quantity_detailed quantity_detailed,
       mtrl.date_required date_required, mtrl.reason_id reason_id,
       mtrl.REFERENCE REFERENCE, mtrl.reference_type_code reference_type_code,
       mtrl.reference_id reference_id, mtrl.project_id project_id,
       mtrl.task_id task_id, mtrl.transaction_header_id transaction_header_id,
       mtrl.line_status line_status, mtrl.status_date status_date,
       mtrl.last_updated_by last_updated_by,
       mtrl.last_update_login last_update_login,
       mtrl.last_update_date last_update_date, mtrl.created_by created_by,
       mtrl.creation_date creation_date, mtrl.request_id request_id,
       mtrl.program_application_id program_application_id,
       mtrl.program_id program_id,
       mtrl.program_update_date program_update_date,
       mtrl.attribute1 attribute1, mtrl.attribute2 attribute2,
       mtrl.attribute3 attribute3, mtrl.attribute4 attribute4,
       mtrl.attribute5 attribute5, mtrl.attribute6 attribute6,
       mtrl.attribute7 attribute7, mtrl.attribute8 attribute8,
       mtrl.attribute9 attribute9, mtrl.attribute10 attribute10,
       mtrl.attribute11 attribute11, mtrl.attribute12 attribute12,
       mtrl.attribute13 attribute13, mtrl.attribute14 attribute14,
       mtrl.attribute15 attribute15,
       mtrl.attribute_category attribute_category,
       mtrl.txn_source_id txn_source_id,
       mtrl.txn_source_line_id txn_source_line_id,
       mtrl.txn_source_line_detail_id txn_source_line_detail_id,
       mtrl.primary_quantity primary_quantity,
       mtrl.to_organization_id to_organization_id,
       mtrl.pick_strategy_id pick_strategy_id,
       mtrl.put_away_strategy_id put_away_strategy_id,
       mtrl.unit_number unit_number,
       mtrl.from_cost_group_id from_cost_group_id,
       cst.cost_group from_cost_group_name,
       mtrl.to_cost_group_id to_cost_group_id,
       cst2.cost_group to_cost_group_name, mtrl.lpn_id lpn_id,
       mtrl.to_lpn_id to_lpn_id, mtrl.reference_detail_id reference_detail_id,
       mtrl.assignment_id assignment_id,
       from_wlpn.license_plate_number lpn_number,
       to_wlpn.license_plate_number to_lpn_number, mtrl.grade_code,
       mtrl.secondary_quantity, mtrl.secondary_quantity_detailed,
       mtrl.secondary_quantity_delivered, mtrl.secondary_required_quantity,
       mtrl.secondary_uom_code, mtt.location_required_flag
  FROM mtl_txn_request_lines mtrl,
       mtl_txn_request_headers mtrh,
       mtl_transaction_types mtt,
       mtl_secondary_inventories mss,
       mtl_secondary_inventories mss1,
       mfg_lookups mfg,
       mfg_lookups mfg2,
       cst_cost_groups cst,
       cst_cost_groups cst2,
       wms_license_plate_numbers from_wlpn,
       wms_license_plate_numbers to_wlpn
 WHERE mtrh.header_id = mtrl.header_id
   AND mtt.transaction_type_id = mtrl.transaction_type_id
   AND mss.secondary_inventory_name(+) = mtrl.from_subinventory_code
   AND mss.organization_id(+) = mtrl.organization_id
   AND mss1.secondary_inventory_name(+) = mtrl.to_subinventory_code
   AND mss1.organization_id(+) = mtrl.organization_id
   AND mfg.lookup_type = 'MTL_TXN_REQUEST_STATUS'
   AND mfg.lookup_code = TO_CHAR (mtrl.line_status)
   AND mfg2.lookup_type = 'MOVE_ORDER_TYPE'
   AND mfg2.lookup_code = TO_CHAR (mtrh.move_order_type)
   AND cst.cost_group_id(+) = mtrl.from_cost_group_id
   AND cst2.cost_group_id(+) = mtrl.to_cost_group_id
   AND mtrl.lpn_id = from_wlpn.lpn_id(+)
   AND mtrl.to_lpn_id = to_wlpn.lpn_id(+)