SELECT BB.OPERATING_UNIT,
 (SELECT NAME FROM HR_ALL_ORGANIZATION_UNITS
WHERE ORGANIZATION_ID = BB.OPERATING_UNIT) AS NAME_OU 
                                     FROM   ORG_ORGANIZATION_DEFINITIONS BB
                                     WHERE  ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM HR_ALL_ORGANIZATION_UNITS
                                     WHERE ORGANIZATION_ID = :IO)