SELECT 
    (
        SELECT HAOU.NAME 
        FROM HR_ALL_ORGANIZATION_UNITS HAOU
        WHERE HAOU.ORGANIZATION_ID = MSIF.ORGANIZATION_ID
    ) AS OU,
    MSIF.SEGMENT1||'-'||
    MSIF.SEGMENT2||'-'||
    MSIF.SEGMENT3||'-'||
    MSIF.SEGMENT4||'-'||
    MSIF.SEGMENT5 AS ITEM_CODE,
    MSIF.DESCRIPTION,
    (
        SELECT GCCK.CONCATENATED_SEGMENTS
        FROM GL_CODE_COMBINATIONS_KFV GCCK
        WHERE CODE_COMBINATION_ID = MSIF.EXPENSE_ACCOUNT
    )AS EXPENSE_ACCOUNT,
    MICV.CATEGORY_CONCAT_SEGS
FROM MTL_SYSTEM_ITEMS_FVL MSIF,
    MTL_ITEM_CATEGORIES_V MICV
WHERE MSIF.ORGANIZATION_ID = 89
AND MSIF.ORGANIZATION_ID = MICV.ORGANIZATION_ID
AND MSIF.INVENTORY_ITEM_ID = MICV.INVENTORY_ITEM_ID
AND CATEGORY_SET_NAME = 'NP Sales Class Category'
ORDER BY OU ASC
 
 