SELECT
B.AE_HEADER_ID,
B.COA,
B.COA1,
B.BEGBAL,
B.CLOSEBAL,
B.COA_DESC,
B.FROM_PERIODE,
B.TO_PERIODE,
B.CATEGORY,
B.SOURCE,
B.NAME,
B.PERIOD_NAME,
B.ENTERED_DEBIT,
B.ENTERED_CREDIT,
B.ENTERED_CURRENCY,
B.RATE,
B.ACCOUNTED_DEBIT,
B.ACCOUNTED_CREDIT,
B.SLA_DESCRIPTION,
B.GL_DATE,
B.VENDOR_NAME,
REPLACE(B.NARASI,'
',' '),
B.TEST11
FROM
(----------Payables-----
SELECT
  XAL.AE_HEADER_ID,
  ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA,
  ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA1,
  (
  SELECT A.CONCAT_DESC 
  FROM COA_DESC A WHERE A.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
  ) AS COA_DESC,
  :p_from_periode as from_periode,
  :p_to_periode as to_periode,
  YNPGL_BEG_BALANCE(UPPER(:p_from_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) begbal,
  YNPGL_CLOSE_BALANCE(UPPER(:p_to_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) closebal,  
  GJH.JE_CATEGORY Category,
  GJH.JE_SOURCE Source,
  GJH.NAME,
  GJH.PERIOD_NAME,
  XAL.ENTERED_DR Entered_Debit,
  XAL.ENTERED_CR Entered_Credit,  
  XAL.CURRENCY_CODE Entered_Currency,
  NVL(XAL.CURRENCY_CONVERSION_RATE,0) RATE,
  NVL(XAL.ACCOUNTED_DR,0) Accounted_Debit,
  NVL(XAL.ACCOUNTED_CR,0) Accounted_Credit,
  XAH.DESCRIPTION SLA_DESCRIPTION,
  XAL.ACCOUNTING_DATE GL_DATE,
  ASUP.VENDOR_NAME,
  (SELECT A.DESCRIPTION
  FROM AP_INVOICES_ALL A
  where a.invoice_id = XTE.source_id_int_1) NARASI,
  (SELECT A.INVOICE_NUM
  FROM AP_INVOICES_ALL A
  where a.invoice_id = XTE.source_id_int_1) TEST11
  FROM
  XLA_AE_HEADERS XAH,
  XLA_AE_LINES XAL,
  GL_JE_LINES GJL,
  GL_IMPORT_REFERENCES GIR,
  GL_JE_HEADERS GJH,
  GL_JE_BATCHES GJB,
  GL_CODE_COMBINATIONS_KFV GCC,
  AP_SUPPLIERS ASUP,
  AP_CHECKS_ALL ACA,
  xla.xla_events xe,
  xla.xla_transaction_entities xte
  --xla_distribution_links xdl
  --ap.ap_invoices_all inv
  --HZ_PARTIES HP
WHERE
  XAH.AE_HEADER_ID=XAL.AE_HEADER_ID AND
  --XAH.AE_HEADER_ID = XDL.AE_HEADER_ID AND
  --XAL.AE_LINE_NUM = XDL.AE_LINE_NUM AND
  GJL.JE_LINE_NUM = GIR.JE_LINE_NUM AND
  GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND
  GJB.JE_BATCH_ID = GJH.JE_BATCH_ID AND
  GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE AND
  GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID AND
  GJL.JE_HEADER_ID=GJH.JE_HEADER_ID  AND
  GJL.CODE_COMBINATION_ID=GCC.CODE_COMBINATION_ID AND
  ASUP.VENDOR_ID(+)=XAL.PARTY_ID AND
  ACA.DOC_SEQUENCE_ID(+)=XAH.DOC_SEQUENCE_ID AND
  ACA.DOC_SEQUENCE_VALUE(+)=XAH.DOC_SEQUENCE_VALUE AND
  XTE.APPLICATION_ID = XAH.APPLICATION_ID
   AND XTE.ENTITY_ID = XAH.ENTITY_ID AND
   XAH.EVENT_ID = XE.EVENT_ID AND
   --XE.EVENT_ID = XDL.EVENT_ID AND
  --ASUP.VENDOR_ID = HP.PARTY_ID AND
  --GCC.SEGMENT5=NVL(:P_ACC_NUM,GCC.SEGMENT5)  AND
  --GCC.CONCATENATED_SEGMENTS = :P_COA AND
  (GCC.SEGMENT2 BETWEEN :P_FROM_PLANT AND :P_TO_PLANT) AND
  (GCC.SEGMENT5 BETWEEN :P_NATURAL_ACCOUNT AND :P_NATURAL_ACCOUNT_2) AND 
  TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_from_periode,'Mon-YY'), 0),'YYYYMM'),'YYYYMM'),TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_to_periode,'Mon-YY'), + 1),'YYYYMM'),'YYYYMM') - 1,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND
  GJH.STATUS='P' AND
  --GJH.PERIOD_NAME = :P_PERIOD AND
  ---GJH.PERIOD_NAME BETWEEN UPPER(:p_from_periode) and UPPER(:p_to_periode) AND
  GJH.JE_SOURCE IN ('Payables')
  AND GJH.ACTUAL_FLAG = 'A'
UNION ALL
------ DATA FROM CASH MANAGEMENT --------------------------------
SELECT
  XAL.AE_HEADER_ID,
  ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA,
  ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA1,
  (
  SELECT A.CONCAT_DESC 
  FROM COA_DESC A WHERE A.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
  ) AS COA_DESC,
  :p_from_periode as from_periode,
  :p_to_periode as to_periode,
  YNPGL_BEG_BALANCE(UPPER(:p_from_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) begbal, 
  YNPGL_CLOSE_BALANCE(UPPER(:p_to_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) closebal,
  GJH.JE_CATEGORY Category,
  GJH.JE_SOURCE Source,
  GJH.NAME,
  GJH.PERIOD_NAME,
  XAL.ENTERED_DR Entered_Debit,
  XAL.ENTERED_CR Entered_Credit,  
  XAL.CURRENCY_CODE Entered_Currency,
  NVL(XAL.CURRENCY_CONVERSION_RATE,0) RATE,
  NVL(XAL.ACCOUNTED_DR,0) Accounted_Debit,
  NVL(XAL.ACCOUNTED_CR,0) Accounted_Credit,
  'Cashflow Number : '||(select cc.cashflow_id from ce_cashflows cc where cc.CASHFLOW_ID = xte.source_id_int_1) ||' / '|| 'Bank Account Transfer Number : '|| 
  (select cc.TRXN_REFERENCE_NUMBER from ce_cashflows cc where cc.CASHFLOW_ID = xte.source_id_int_1) as SLA_DESCRIPTION,
  XAL.ACCOUNTING_DATE GL_DATE,
  '' VENDOR_NAME,
  (select
   cba.BANK_ACCOUNT_NAME
   from ce_bank_accounts cba
   where cba.BANK_ACCOUNT_ID = (select cc.cashflow_bank_account_id from ce_cashflows cc where cc.CASHFLOW_ID = xte.source_id_int_1))||' / '|| (select
   cba.BANK_ACCOUNT_NAME
   from ce_bank_accounts cba
   where cba.BANK_ACCOUNT_ID = (select cc.counterparty_bank_account_id from ce_cashflows cc where cc.CASHFLOW_ID = xte.source_id_int_1))||' / '||(select cc.DESCRIPTION from ce_cashflows cc where cc.CASHFLOW_ID = xte.source_id_int_1) 
   AS NARASI,
   '' AS TEST11
FROM
  XLA_AE_HEADERS XAH,
  XLA_AE_LINES XAL,
  GL_JE_LINES GJL,
  GL_IMPORT_REFERENCES GIR,
  GL_JE_HEADERS GJH,
  GL_CODE_COMBINATIONS_KFV GCC,
  GL_JE_BATCHES GJB,
  xla.xla_transaction_entities xte,
  XLA_EVENTS XE
  --XLA_DISTRIBUTION_LINKS XDL
WHERE
  XAH.AE_HEADER_ID=XAL.AE_HEADER_ID AND
  GJL.JE_LINE_NUM = GIR.JE_LINE_NUM AND
  GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND
  GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE AND
  GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID AND
  GJL.JE_HEADER_ID=GJH.JE_HEADER_ID  AND
  GJB.JE_BATCH_ID = GJH.JE_BATCH_ID AND
  GJL.CODE_COMBINATION_ID=GCC.CODE_COMBINATION_ID AND
  XAH.EVENT_ID = XE.EVENT_ID AND
  --GCC.CONCATENATED_SEGMENTS = :P_COA AND
  (GCC.SEGMENT2 BETWEEN :P_FROM_PLANT AND :P_TO_PLANT) AND
  (GCC.SEGMENT5 BETWEEN :P_NATURAL_ACCOUNT AND :P_NATURAL_ACCOUNT_2) AND 
  --TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(:P_FROM_DATE,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(:P_TO_DATE,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND
  TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_from_periode,'Mon-YY'), 0),'YYYYMM'),'YYYYMM'),TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_to_periode,'Mon-YY'), + 1),'YYYYMM'),'YYYYMM') - 1,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND
  --GJH.PERIOD_NAME IN ('APR-11-12','MAY-11-12','JUN-11-12','JUL-11-12') AND
  GJH.STATUS='P' AND
  --GJH.PERIOD_NAME = :P_PERIOD AND
  --GJH.PERIOD_NAME BETWEEN UPPER(:p_from_periode) and UPPER(:p_to_periode) AND
  GJH.JE_SOURCE='Cash Management' AND
  GJH.JE_CATEGORY='Bank Transfers'
  AND GJH.ACTUAL_FLAG = 'A'
AND XAH.APPLICATION_ID = XTE.APPLICATION_ID
AND XTE.ENTITY_ID = XAH.ENTITY_ID
--AND XAH.AE_HEADER_ID = XDL.AE_HEADER_ID
--AND XAL.AE_LINE_NUM = XDL.AE_LINE_NUM
--AND XE.EVENT_ID = XDL.EVENT_ID
UNION ALL
-------------------Data from Receivable --------------------------------
SELECT
  XAL.AE_HEADER_ID, 
  ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA,
  ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA1,
  (
  SELECT A.CONCAT_DESC 
  FROM COA_DESC A WHERE A.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
  ) AS COA_DESC,
  :p_from_periode as from_periode,
  :p_to_periode as to_periode,
YNPGL_BEG_BALANCE(UPPER(:p_from_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) begbal, 
  YNPGL_CLOSE_BALANCE(UPPER(:p_to_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) closebal,
      GJH.JE_CATEGORY Category,
      GJH.JE_SOURCE Source,
      GJH.NAME,
      GJH.PERIOD_NAME,
      XAL.ENTERED_DR Entered_Debit,
      XAL.ENTERED_CR Entered_Credit,  
      XAL.CURRENCY_CODE Entered_Currency,
      NVL(XAL.CURRENCY_CONVERSION_RATE,0) RATE,
      NVL(XAL.ACCOUNTED_DR,0) Accounted_Debit,
      NVL(XAL.ACCOUNTED_CR,0) Accounted_Credit,     
      XAH.DESCRIPTION SLA_DESCRIPTION,      
      XAL.ACCOUNTING_DATE GL_DATE,
      NVL((SELECT AC.CUSTOMER_NAME
      FROM AR_CUSTOMERS AC WHERE AC.CUSTOMER_ID=XAL.PARTY_ID),(SELECT AC.CUSTOMER_NAME
      FROM AR_CUSTOMERS AC WHERE AC.CUSTOMER_ID=(SELECT acr.PAY_FROM_CUSTOMER FROM AR_CASH_RECEIPTS_ALL ACR
      WHERE --ACR.DOC_SEQUENCE_ID=XAH.DOC_SEQUENCE_ID AND
      ACR.CASH_RECEIPT_ID=XTE.source_id_int_1))) CUSTOMER_NAME,
      (SELECT REPLACE(ACR.COMMENTS,'
      ',' ') FROM AR_CASH_RECEIPTS_ALL ACR
      WHERE --ACR.DOC_SEQUENCE_ID=XAH.DOC_SEQUENCE_ID AND
      ACR.CASH_RECEIPT_ID=XTE.source_id_int_1
      ) NARASI,
      '' AS TEST11
  FROM GL_JE_BATCHES GJB,
       GL_JE_HEADERS GJH,
       GL_JE_LINES GJL,
       GL_CODE_COMBINATIONS_KFV GCC,
       GL_IMPORT_REFERENCES GIR,
       XLA_AE_LINES XAL,
       XLA_AE_HEADERS XAH,
       XLA.XLA_TRANSACTION_ENTITIES XTE,
       XLA_EVENTS XE
       --XLA_DISTRIBUTION_LINKS XDL
WHERE GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
   AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
   AND GJL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
   AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
   AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
   AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
   AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
   AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
   AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
   AND XTE.ENTITY_ID = XAH.ENTITY_ID
   AND XAH.EVENT_ID = XE.EVENT_ID
   --AND XAH.AE_HEADER_ID = XDL.AE_HEADER_ID
   --AND XAL.AE_LINE_NUM = XDL.AE_LINE_NUM
   --AND XE.EVENT_ID = XDL.EVENT_ID
   AND GJL.STATUS = 'P'
   --AND GCC.SEGMENT5 = NVL (:P_ACC_NUM, GCC.SEGMENT5)
   --AND GCC.CONCATENATED_SEGMENTS = :P_COA
   AND (GCC.SEGMENT2 BETWEEN :P_FROM_PLANT AND :P_TO_PLANT)
   AND (GCC.SEGMENT5 BETWEEN :P_NATURAL_ACCOUNT AND :P_NATURAL_ACCOUNT_2) 
   /*AND TRUNC (GJH.DEFAULT_EFFECTIVE_DATE)
          BETWEEN NVL (:P_FROM_DATE, TRUNC (GJH.DEFAULT_EFFECTIVE_DATE))
              AND NVL (:P_TO_DATE, TRUNC (GJH.DEFAULT_EFFECTIVE_DATE))*/
  --AND GJH.PERIOD_NAME = :P_PERIOD 
  AND TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_from_periode,'Mon-YY'), 0),'YYYYMM'),'YYYYMM'),TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_to_periode,'Mon-YY'), + 1),'YYYYMM'),'YYYYMM') - 1,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE))
  --AND GJH.PERIOD_NAME BETWEEN UPPER(:p_from_periode) and UPPER(:p_to_periode) 
  AND GJH.JE_SOURCE = 'Receivables'
  AND GJH.ACTUAL_FLAG = 'A'
  UNION ALL
 ---------------- Manual, Spreadsheet, Recurring, Revaluation, MassAllocations, Transportation Cost, AutoCopy  -----------------------
SELECT
0 AE_HEADER_ID, 
  ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA,
  ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA1,
  (
  SELECT A.CONCAT_DESC 
  FROM COA_DESC A WHERE A.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
  ) AS COA_DESC,
  :p_from_periode as from_periode,
  :p_to_periode as to_periode,
YNPGL_BEG_BALANCE(UPPER(:p_from_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) begbal, 
  YNPGL_CLOSE_BALANCE(UPPER(:p_to_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) closebal,
       GJH.JE_CATEGORY Category,
       GJH.JE_SOURCE Source,
       GJH.NAME,
       GJH.PERIOD_NAME,
       GJL.ENTERED_DR Entered_Debit,
       GJL.ENTERED_CR Entered_Credit,  
       '' Entered_Currency,
       NULL RATE,
       NVL(GJL.ACCOUNTED_DR,0) ACCOUNTED_DEBIT,
       NVL(GJL.ACCOUNTED_CR,0) ACCOUNTED_CREDIT,
        '' SLA_DESCRIPTION,
        GJH.DEFAULT_EFFECTIVE_DATE GL_DATE,
        '' VENDOR_NAME,
        GJL.DESCRIPTION AS NARASI,
        '' AS TEST11       
 FROM GL_JE_BATCHES GJB,
      GL_JE_HEADERS GJH,
      GL_JE_LINES GJL,
      GL_CODE_COMBINATIONS_KFV GCC
 WHERE GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
   AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
   AND GJL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
   AND GJL.STATUS = 'P'
   --AND GCC.SEGMENT5 = NVL (:P_ACC_NUM, GCC.SEGMENT5)
   --AND GCC.CONCATENATED_SEGMENTS = :P_COA 
   AND (GCC.SEGMENT2 BETWEEN :P_FROM_PLANT AND :P_TO_PLANT)  
   AND (GCC.SEGMENT5 BETWEEN :P_NATURAL_ACCOUNT AND :P_NATURAL_ACCOUNT_2) 
   /*AND TRUNC (GJH.DEFAULT_EFFECTIVE_DATE)
          BETWEEN NVL (:P_FROM_DATE, TRUNC (GJH.DEFAULT_EFFECTIVE_DATE))
              AND NVL (:P_TO_DATE, TRUNC (GJH.DEFAULT_EFFECTIVE_DATE))*/
   AND (GJH.JE_SOURCE IN ('Manual','Spreadsheet','Recurring','Revaluation','MassAllocations','Transportation Cost','AutoCopy','2')
   OR GJH.JE_SOURCE = 'Assets' AND SUBSTR(GJB.NAME,1,8) = 'Reverses')
   --AND GJH.PERIOD_NAME = :P_PERIOD
   --AND GJH.PERIOD_NAME BETWEEN UPPER(:p_from_periode) and UPPER(:p_to_periode) 
   AND TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_from_periode,'Mon-YY'), 0),'YYYYMM'),'YYYYMM'),TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_to_periode,'Mon-YY'), + 1),'YYYYMM'),'YYYYMM') - 1,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE))
   AND GJH.ACTUAL_FLAG = 'A'
UNION ALL
-----ALL OTHER SOURCES OTHER THAN ABOVE OR INVENTORY RECEIVING AND SALES INVOICE----------
SELECT
XAL.AE_HEADER_ID,
  ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA,
  ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA1,
  (
  SELECT A.CONCAT_DESC 
  FROM COA_DESC A WHERE A.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
  ) AS COA_DESC,
  :p_from_periode as from_periode,
  :p_to_periode as to_periode,
YNPGL_BEG_BALANCE(UPPER(:p_from_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) begbal, 
  YNPGL_CLOSE_BALANCE(UPPER(:p_to_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) closebal, 
  GJH.JE_CATEGORY Category,
  GJH.JE_SOURCE Source,
  GJH.NAME,
  GJH.PERIOD_NAME,
  XAL.ENTERED_DR Entered_Debit,
  XAL.ENTERED_CR Entered_Credit,  
  XAL.CURRENCY_CODE Entered_Currency,
  NVL(XAL.CURRENCY_CONVERSION_RATE,0) RATE,
  NVL(XAL.ACCOUNTED_DR,0) Accounted_Debit,
  NVL(XAL.ACCOUNTED_CR,0) Accounted_Credit,
  (select a.CONCATENATED_SEGMENTS from
    mtl_system_items_kfv a
 where
 a.INVENTORY_ITEM_ID = mmt.INVENTORY_ITEM_ID
 and a.ORGANIZATION_ID = mmt.ORGANIZATION_ID) ||'/'|| (select ooha.ORDER_NUMBER from 
  oe_order_headers_all ooha 
 ,oe_order_lines_all oola  
where ooha.HEADER_ID=oola.HEADER_ID 
and oola.LINE_ID=MMT.TRX_SOURCE_LINE_ID ) ||'/'|| (select a.NAME from wsh_new_deliveries a
where a.DELIVERY_ID = mmt.TRX_SOURCE_DELIVERY_ID ) SLA_DESCRIPTION,
  XAL.ACCOUNTING_DATE GL_DATE,
  '' VENDOR_NAME,
  '' AS NARASI,
  '' AS TEST11
  FROM
  XLA_AE_HEADERS XAH,
  XLA_AE_LINES XAL,
  XLA_EVENTS XE,
  xla_transaction_entities_upg xte,
  GL_JE_LINES GJL,
  GL_IMPORT_REFERENCES GIR,
  GL_JE_HEADERS GJH,
  GL_CODE_COMBINATIONS_KFV GCC,
  GL_JE_BATCHES GJB,
  mtl_material_transactions mmt
  --XLA_DISTRIBUTION_LINKS XDL
WHERE
  XAH.AE_HEADER_ID=XAL.AE_HEADER_ID AND
  XAH.EVENT_ID = XE.EVENT_ID AND
  XAH.APPLICATION_ID = XE.APPLICATION_ID AND
  xte.entity_id = xe.entity_id AND
  --XAH.AE_HEADER_ID = XDL.AE_HEADER_ID AND 
  --XAL.AE_LINE_NUM = XDL.AE_LINE_NUM AND
  --XE.EVENT_ID = XDL.EVENT_ID AND
  xte.SOURCE_ID_INT_1 = mmt.TRANSACTION_ID (+) and
  GJL.JE_LINE_NUM = GIR.JE_LINE_NUM AND
  GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND
  GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE AND
  GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID AND
  GJL.JE_HEADER_ID=GJH.JE_HEADER_ID  AND
  GJL.CODE_COMBINATION_ID=GCC.CODE_COMBINATION_ID AND
  GJB.JE_BATCH_ID = GJH.JE_BATCH_ID AND
  --GCC.SEGMENT5=NVL(:P_ACC_NUM,GCC.SEGMENT5)  AND
  --GCC.CONCATENATED_SEGMENTS = :P_COA AND 
  (GCC.SEGMENT2 BETWEEN :P_FROM_PLANT AND :P_TO_PLANT) AND 
  (GCC.SEGMENT5 BETWEEN :P_NATURAL_ACCOUNT AND :P_NATURAL_ACCOUNT_2)AND 
  --TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(:P_FROM_DATE,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(:P_TO_DATE,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND
  GJH.STATUS='P' AND
  --GJH.PERIOD_NAME = :P_PERIOD AND
  --GJH.PERIOD_NAME BETWEEN UPPER(:p_from_periode) and UPPER(:p_to_periode) AND 
  TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_from_periode,'Mon-YY'), 0),'YYYYMM'),'YYYYMM'),TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_to_periode,'Mon-YY'), + 1),'YYYYMM'),'YYYYMM') - 1,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND
  GJH.JE_SOURCE NOT IN ('Receivables','Payables','Cash Management','Assets','Cost Management') AND
  GJH.JE_CATEGORY IN ('Sales Invoices') AND
  GJH.ACTUAL_FLAG = 'A'
  UNION ALL
  SELECT
  XAL.AE_HEADER_ID,
  ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA,
  ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA1,
  (
  SELECT A.CONCAT_DESC 
  FROM COA_DESC A WHERE A.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
  ) AS COA_DESC,
  :p_from_periode as from_periode,
  :p_to_periode as to_periode,
YNPGL_BEG_BALANCE(UPPER(:p_from_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) begbal, 
  YNPGL_CLOSE_BALANCE(UPPER(:p_to_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) closebal, 
  GJH.JE_CATEGORY Category,
  GJH.JE_SOURCE Source,
  GJH.NAME,
  GJH.PERIOD_NAME,
  XAL.ENTERED_DR Entered_Debit,
  XAL.ENTERED_CR Entered_Credit,  
  XAL.CURRENCY_CODE Entered_Currency,
  NVL(XAL.CURRENCY_CONVERSION_RATE,0) RATE,
  NVL(XAL.ACCOUNTED_DR,0) Accounted_Debit,
  NVL(XAL.ACCOUNTED_CR,0) Accounted_Credit,
 'Item : '||(SELECT 
  MSIK.CONCATENATED_SEGMENTS
  FROM
  MTL_SYSTEM_ITEMS_KFV MSIK  
  WHERE rownum = 1 and MSIK.INVENTORY_ITEM_ID = GXEH.INVENTORY_ITEM_ID
  AND MSIK.ORGANIZATION_ID = 89) ||
  ' PO: '||(select a.SEGMENT1 from po_headers_all a
where rownum = 1 and a.PO_HEADER_ID = (select distinct po_header_id from rcv_shipment_lines rsl where rownum = 1 and rsl.shipment_header_id = gxeh.source_document_id )) ||' - '||
'Receipt Number: '||(SELECT rsh.RECEIPT_NUM 
FROM RCV_SHIPMENT_HEADERS rsh
WHERE rownum = 1 and rsh.SHIPMENT_HEADER_ID =
gxeh.source_document_id) SLA_DESCRIPTION,
  XAL.ACCOUNTING_DATE GL_DATE,  
  (SELECT
  AP.VENDOR_NAME
  FROM
  AP_SUPPLIERS AP,
  AP_SUPPLIER_SITES_ALL ASS
  WHERE AP.VENDOR_ID = (SELECT
    a.VENDOR_ID
    FROM
    RCV_SHIPMENT_HEADERS A
    WHERE A.SHIPMENT_HEADER_ID = gxeh.source_document_id)
    AND ROWNUM = 1) VENDOR_NAME,
  '' AS NARASI,
  '' AS TEST11
  FROM
  XLA_AE_HEADERS XAH,
  XLA_AE_LINES XAL,
  XLA_EVENTS XE,
  xla.xla_transaction_entities xte,
  GL_JE_LINES GJL,
  GL_IMPORT_REFERENCES GIR,
  GL_JE_HEADERS GJH,
  GL_CODE_COMBINATIONS_KFV GCC,
  GL_JE_BATCHES GJB,
  --mtl_material_transactions mmt,
  XLA_DISTRIBUTION_LINKS XDL,
  --rcv_transactions rcvt,
  gmf_xla_extract_headers gxeh
  --rcv_receiving_sub_ledger rrsl
WHERE
  XAH.AE_HEADER_ID=XAL.AE_HEADER_ID AND
  XAH.EVENT_ID = XE.EVENT_ID AND
  --xe.application_id = xte.application_id AND
  XAH.APPLICATION_ID = XE.APPLICATION_ID AND
  xte.entity_id = xe.entity_id AND
  XAH.AE_HEADER_ID = XDL.AE_HEADER_ID AND 
  XAL.AE_LINE_NUM = XDL.AE_LINE_NUM AND
  XE.EVENT_ID = XDL.EVENT_ID AND
  --xte.SOURCE_ID_INT_1 = mmt.TRANSACTION_ID (+) and
  GJL.JE_LINE_NUM = GIR.JE_LINE_NUM AND
  GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND
  GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE AND
  GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID AND
  --gir.gl_sl_link_id = rrsl.gl_sl_link_id and
  GJL.JE_HEADER_ID=GJH.JE_HEADER_ID  AND
  GJL.CODE_COMBINATION_ID=GCC.CODE_COMBINATION_ID AND
  GJB.JE_BATCH_ID = GJH.JE_BATCH_ID AND
  gxeh.event_id = xdl.EVENT_ID and
  gxeh.entity_code = xte.ENTITY_CODE and
  --xte.source_id_int_1 = rcvt.transaction_id (+) AND
  --XTE.ENTITY_CODE = 'PURCHASING' AND
  XDL.SOURCE_DISTRIBUTION_TYPE = XTE.ENTITY_CODE AND
  XDL.APPLICATION_ID = XTE.APPLICATION_ID AND
  XDL.EVENT_CLASS_CODE = XTE.SOURCE_ID_CHAR_1 AND
  XDL.EVENT_CLASS_CODE = GXEH.EVENT_CLASS_CODE AND
  --XTE.SOURCE_ID_CHAR_1 = 'RECEIVE' AND
  --XDL.SOURCE_DISTRIBUTION_ID_NUM_1 = rrsl.rcv_sub_ledger_id (+) AND
  --GCC.SEGMENT5=NVL(:P_ACC_NUM,GCC.SEGMENT5)  AND
  --GCC.CONCATENATED_SEGMENTS = :P_COA AND 
  (GCC.SEGMENT2 BETWEEN :P_FROM_PLANT AND :P_TO_PLANT) AND 
  (GCC.SEGMENT5 BETWEEN :P_NATURAL_ACCOUNT AND :P_NATURAL_ACCOUNT_2)AND 
  --TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(:P_FROM_DATE,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(:P_TO_DATE,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND
  GJH.STATUS='P' AND
  --GJH.PERIOD_NAME = :P_PERIOD AND
  --GJH.PERIOD_NAME BETWEEN UPPER(:p_from_periode) and UPPER(:p_to_periode) AND 
  TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_from_periode,'Mon-YY'), 0),'YYYYMM'),'YYYYMM'),TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_to_periode,'Mon-YY'), + 1),'YYYYMM'),'YYYYMM') - 1,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND
  GJH.JE_SOURCE NOT IN ('Receivables','Payables','Cash Management','Assets','Cost Management') AND
  GJH.JE_CATEGORY = 'Receiving' AND
  GJH.ACTUAL_FLAG = 'A'
  UNION ALL
--------COST MANAGEMENT-------------------------------------------
  SELECT
  XAL.AE_HEADER_ID,
   ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA,
    ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA1,
  (
  SELECT A.CONCAT_DESC 
  FROM COA_DESC A WHERE A.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
  ) AS COA_DESC,
  :p_from_periode as from_periode,
  :p_to_periode as to_periode,
YNPGL_BEG_BALANCE(UPPER(:p_from_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) begbal, 
  YNPGL_CLOSE_BALANCE(UPPER(:p_to_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) closebal, 
  GJH.JE_CATEGORY Category,
  GJH.JE_SOURCE Source,
  GJH.NAME,
  GJH.PERIOD_NAME,
  XAL.ENTERED_DR Entered_Debit,
  XAL.ENTERED_CR Entered_Credit,  
  XAL.CURRENCY_CODE Entered_Currency,
  NVL(XAL.CURRENCY_CONVERSION_RATE,0) RATE,
  NVL(XAL.ACCOUNTED_DR,0) Accounted_Debit,
  NVL(XAL.ACCOUNTED_CR,0) Accounted_Credit,
  'Item : '||(select
  msi.CONCATENATED_SEGMENTS
  from
  rcv_transactions rt,
  rcv_shipment_lines rsl,
  mtl_system_items_kfv msi
  where rt.SHIPMENT_LINE_ID = rsl.SHIPMENT_LINE_ID
  and msi.INVENTORY_ITEM_ID = rsl.ITEM_ID
  and msi.ORGANIZATION_ID = 89
  and rt.TRANSACTION_ID = rrsl.rcv_transaction_id) ||
  ' PO: '||(select a.SEGMENT1 from po_headers_all a
where a.PO_HEADER_ID = rrsl.reference2) ||' - '||
'Receipt Number: '||(select
rsh.RECEIPT_NUM
from
rcv_transactions rt,
rcv_shipment_headers rsh
where rt.SHIPMENT_HEADER_ID = rsh.SHIPMENT_HEADER_ID
and rt.TRANSACTION_ID = rrsl.rcv_transaction_id) SLA_DESCRIPTION,
  XAL.ACCOUNTING_DATE GL_DATE,
(select
ap.VENDOR_NAME
from
rcv_transactions rt,
rcv_shipment_headers rsh,
ap_suppliers ap
where ROWNUM = 1 AND rt.SHIPMENT_HEADER_ID = rsh.SHIPMENT_HEADER_ID
and rt.VENDOR_ID = ap.VENDOR_ID
and rt.TRANSACTION_ID = rrsl.rcv_transaction_id) VENDOR_NAME,
  (select listagg
(a.NOTE_TO_RECEIVER, ' , ') within group (order by a.line_location_id)
from
po_line_locations_all a
where a.PO_HEADER_ID = rrsl.reference2
and a.PO_LINE_ID = (select b.PO_LINE_ID from po_distributions_all b where b.PO_DISTRIBUTION_ID = rrsl.reference3)) AS NARASI,
'' AS TEST11
FROM
  XLA_AE_HEADERS XAH,
  XLA_AE_LINES XAL,
  XLA_EVENTS XE,
  XLA_DISTRIBUTION_LINKS XDL,
  GL_JE_LINES GJL,
  GL_IMPORT_REFERENCES GIR,
  GL_JE_HEADERS GJH,
  GL_CODE_COMBINATIONS_KFV GCC,
  GL_JE_BATCHES GJB, rcv_receiving_sub_ledger rrsl--, rcv_transactions rt, po_distributions_all pd
WHERE
  XAH.AE_HEADER_ID=XAL.AE_HEADER_ID AND
  XAH.AE_HEADER_ID = XDL.AE_HEADER_ID AND
  XAL.AE_LINE_NUM = XDL.AE_LINE_NUM AND
  XAH.EVENT_ID = XE.EVENT_ID AND
  XE.EVENT_ID = XDL.EVENT_ID AND
  XAH.APPLICATION_ID = XE.APPLICATION_ID AND
  XDL.SOURCE_DISTRIBUTION_ID_NUM_1 = rrsl.rcv_sub_ledger_id (+) AND
  --pd.po_distribution_id = rt.PO_DISTRIBUTION_ID and 
  --rt.transaction_id = rrsl.rcv_transaction_id AND
  --rt.PO_DISTRIBUTION_ID = rrsl.reference3 and 
  GJL.JE_LINE_NUM = GIR.JE_LINE_NUM AND
  GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND
  GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE AND
  GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID AND
  GJL.JE_HEADER_ID=GJH.JE_HEADER_ID  AND
  GJL.CODE_COMBINATION_ID=GCC.CODE_COMBINATION_ID AND
  GJB.JE_BATCH_ID = GJH.JE_BATCH_ID AND
  --GCC.SEGMENT5=NVL(:P_ACC_NUM,GCC.SEGMENT5)  AND
  --GCC.CONCATENATED_SEGMENTS = :P_COA AND
  (GCC.SEGMENT2 BETWEEN :P_FROM_PLANT AND :P_TO_PLANT) AND 
  (GCC.SEGMENT5 BETWEEN :P_NATURAL_ACCOUNT AND :P_NATURAL_ACCOUNT_2) AND 
  --TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(:P_FROM_DATE,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(:P_TO_DATE,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND
  GJH.STATUS='P' AND
  --GJH.PERIOD_NAME = :P_PERIOD AND
  TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_from_periode,'Mon-YY'), 0),'YYYYMM'),'YYYYMM'),TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_to_periode,'Mon-YY'), + 1),'YYYYMM'),'YYYYMM') - 1,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND
  --GJH.PERIOD_NAME BETWEEN UPPER(:p_from_periode) and UPPER(:p_to_periode) AND 
  GJH.JE_SOURCE = 'Cost Management'
  AND GJH.ACTUAL_FLAG = 'A' 
 UNION ALL
  -----Assets-----
  SELECT
  XAL.AE_HEADER_ID,
    ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA,
    ynp_coa(GCC.CONCATENATED_SEGMENTS) AS COA1,
  (
  SELECT A.CONCAT_DESC 
  FROM COA_DESC A WHERE A.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
  ) AS COA_DESC,
  :p_from_periode as from_periode,
  :p_to_periode as to_periode,
  YNPGL_BEG_BALANCE(UPPER(:p_from_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) begbal,
  YNPGL_CLOSE_BALANCE(UPPER(:p_to_periode),GJH.LEDGER_ID,GCC.CODE_COMBINATION_ID) closebal,
  GJH.JE_CATEGORY Category,
  GJH.JE_SOURCE Source,
  GJH.NAME,
  GJH.PERIOD_NAME,
  XAL.ENTERED_DR Entered_Debit,
  XAL.ENTERED_CR Entered_Credit,  
  XAL.CURRENCY_CODE Entered_Currency,
  NVL(XAL.CURRENCY_CONVERSION_RATE,0) RATE,
  NVL(XAL.ACCOUNTED_DR,0) Accounted_Debit,
  NVL(XAL.ACCOUNTED_CR,0) Accounted_Credit,
  DECODE(XAH.EVENT_TYPE_CODE,'DEPRECIATION',XDL.SOURCE_DISTRIBUTION_ID_NUM_1
  ,'ADDITIONS',(SELECT A.ASSET_NUMBER FROM FA_TRANSACTION_HISTORY_TRX_V A WHERE A.TRANSACTION_HEADER_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1 
AND A.TRANSACTION_TYPE = 'Addition')) 
  ||'-'||
  DECODE(XAH.EVENT_TYPE_CODE,'DEPRECIATION',
  (SELECT A.DESCRIPTION 
  FROM 
  FA_ADDITIONS A
  WHERE A.ASSET_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1),
  'ADDITIONS',(SELECT A.DESCRIPTION FROM FA_TRANSACTION_HISTORY_TRX_V A WHERE A.TRANSACTION_HEADER_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1 
AND A.TRANSACTION_TYPE = 'Addition'))
  ||'-'
  ||
  DECODE(XAH.EVENT_TYPE_CODE,'DEPRECIATION',
  (SELECT A.PERIOD_NAME
  FROM
  FA_DEPRN_PERIODS A WHERE A.PERIOD_COUNTER = XDL.SOURCE_DISTRIBUTION_ID_NUM_2
  AND A.BOOK_TYPE_CODE = XDL.SOURCE_DISTRIBUTION_ID_CHAR_4),
  'ADDITIONS',(SELECT A.PERIOD_ENTERED FROM FA_TRANSACTION_HISTORY_TRX_V A WHERE A.TRANSACTION_HEADER_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1 
AND A.TRANSACTION_TYPE = 'Addition'))
  ||'-'
  ||
  DECODE(XAH.EVENT_TYPE_CODE,'DEPRECIATION',
  XDL.SOURCE_DISTRIBUTION_ID_CHAR_4,
  'ADDITIONS',(SELECT A.BOOK_TYPE_CODE FROM FA_TRANSACTION_HEADERS A WHERE A.TRANSACTION_HEADER_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
  AND A.TRANSACTION_TYPE_CODE = 'ADDITION')) SLA_DESCRIPTION,
  XAL.ACCOUNTING_DATE GL_DATE,
  ASUP.VENDOR_NAME,
  '' AS NARASI,
  '' AS TEST11      
FROM
  XLA_AE_HEADERS XAH,
  XLA_AE_LINES XAL,
  XLA_EVENTS XE,
  XLA_DISTRIBUTION_LINKS XDL,
  GL_JE_LINES GJL,
  GL_IMPORT_REFERENCES GIR,
  GL_JE_HEADERS GJH,
  GL_JE_BATCHES GJB,
  GL_CODE_COMBINATIONS_KFV GCC,
  AP_SUPPLIERS ASUP,
  AP_CHECKS_ALL ACA
  --HZ_PARTIES HP
WHERE
  XAH.AE_HEADER_ID=XAL.AE_HEADER_ID AND
  XAH.EVENT_ID = XE.EVENT_ID AND
  XAH.APPLICATION_ID = XE.APPLICATION_ID AND
  XAH.AE_HEADER_ID = XDL.AE_HEADER_ID AND
  XAH.EVENT_ID = XDL.EVENT_ID AND
  XAL.AE_LINE_NUM = XDL.AE_LINE_NUM AND
  GJL.JE_LINE_NUM = GIR.JE_LINE_NUM AND
  GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND
  GJB.JE_BATCH_ID = GJH.JE_BATCH_ID AND
  GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE AND
  GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID AND
  GJL.JE_HEADER_ID=GJH.JE_HEADER_ID  AND
  GJL.CODE_COMBINATION_ID=GCC.CODE_COMBINATION_ID AND
  ASUP.VENDOR_ID(+)=XAL.PARTY_ID AND
  ACA.DOC_SEQUENCE_ID(+)=XAH.DOC_SEQUENCE_ID AND
  ACA.DOC_SEQUENCE_VALUE(+)=XAH.DOC_SEQUENCE_VALUE AND
  --ASUP.VENDOR_ID = HP.PARTY_ID AND
  --GCC.SEGMENT5=NVL(:P_ACC_NUM,GCC.SEGMENT5)  AND
  --GCC.CONCATENATED_SEGMENTS = :P_COA AND
  (GCC.SEGMENT2 BETWEEN :P_FROM_PLANT AND :P_TO_PLANT) AND 
  (GCC.SEGMENT5 BETWEEN :P_NATURAL_ACCOUNT AND :P_NATURAL_ACCOUNT_2) AND
  --TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(:P_FROM_DATE,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(:P_TO_DATE,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND
  TRUNC(GJH.DEFAULT_EFFECTIVE_DATE) BETWEEN NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_from_periode,'Mon-YY'), 0),'YYYYMM'),'YYYYMM'),TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND NVL(TO_DATE(TO_CHAR(ADD_MONTHS(TO_DATE(:p_to_periode,'Mon-YY'), + 1),'YYYYMM'),'YYYYMM') - 1,TRUNC(GJH.DEFAULT_EFFECTIVE_DATE)) AND
  GJH.STATUS='P' AND
  --GJH.PERIOD_NAME = :P_PERIOD AND
  --GJH.PERIOD_NAME BETWEEN UPPER(:p_from_periode) and UPPER(:p_to_periode) AND
  GJH.JE_SOURCE IN ('Assets')
  AND GJH.ACTUAL_FLAG = 'A') B
  ORDER BY B.GL_DATE ASC