SELECT (SELECT SEGMENT1||'-'||SEGMENT2||'-'||SEGMENT3||'-'||SEGMENT4||'-'||SEGMENT5 
            FROM MTL_SYSTEM_ITEMS_B 
            WHERE INVENTORY_ITEM_ID = C.INVENTORY_ITEM_ID 
            AND ORGANIZATION_ID = C.ORGANIZATION_ID) as ITEM_CODE,
        C.ITEM_DESCRIPTION as  DESCRIPTION,
        A.NAME as DO_NUMBER, 
        A.INITIAL_PICKUP_DATE as TANGGAL_KIRIM, 
        C.SUBINVENTORY,
        C.LOT_NUMBER, 
        C.REQUESTED_QUANTITY_UOM as UOM, 
        CASE WHEN C.SHIPPED_QUANTITY IS NULL THEN
                C.REQUESTED_QUANTITY
             ELSE C.SHIPPED_QUANTITY
        END as QTY_KIRIM,
        (SELECT
               CASE
                   WHEN D.ACCOUNT_NAME IS NULL OR D.ACCOUNT_NAME =''  THEN
                        d.attribute1
                   ELSE D.ACCOUNT_NAME
               END
          FROM hz_cust_accounts d
          WHERE d.cust_account_id =  A.CUSTOMER_ID) as NAMA_CUSTOMER,
          TO_DATE (:TGL1, 'RRRR/MM/DD HH24:MI:SS') as TANGGAL_AWAL,
          TO_DATE (:TGL2, 'RRRR/MM/DD HH24:MI:SS') as TANGGAL_AKHIR,
          (SELECT NAME 
            FROM HR_ALL_ORGANIZATION_UNITS
            WHERE ORGANIZATION_ID = (SELECT OPERATING_UNIT
                                    FROM ORG_ORGANIZATION_DEFINITIONS OOD
                                    WHERE ORGANIZATION_ID = A.ORGANIZATION_ID )
            ) OU_NAME
FROM WSH_NEW_DELIVERIES A, WSH_DELIVERY_ASSIGNMENTS B, WSH_DELIVERY_DETAILS C
WHERE A.DELIVERY_ID = B.DELIVERY_ID
AND B.DELIVERY_DETAIL_ID = C.DELIVERY_DETAIL_ID
--AND C.RELEASED_STATUS = 'C'
AND (A.INITIAL_PICKUP_DATE BETWEEN TRUNC(TO_DATE (:TGL1, 'RRRR/MM/DD HH24:MI:SS'))
                    AND TRUNC(TO_DATE (:TGL2,'RRRR/MM/DD HH24:MI:SS')+1))
AND C.LOT_NUMBER IS NOT NULL
AND (SELECT OPERATING_UNIT
        FROM ORG_ORGANIZATION_DEFINITIONS OOD
        WHERE ORGANIZATION_ID = A.ORGANIZATION_ID ) = :OU
ORDER BY C.INVENTORY_ITEM_ID, TANGGAL_KIRIM, DO_NUMBER