SELECT PP.PLAN_CMPLT_DATE,
       PP.LOT_NUMBER,
       PP.BATCH_NO,
       PP.INVENTORY_ITEM_ID,
       PP.ITEM_CODE,
       PP.DESCRIPTION,
       PP.DETAIL_LOT_NUMBER,
       PP.ACTUAL_QTY,
       PP.TRANSACTION_UOM,
       PP.TYPE,
       YTIH.TANGGAL_KIRIM,
       YTIH.DO_NUMBER,
       YTIH.QTY_KIRIM
FROM ( 
    SELECT GBH.PLAN_CMPLT_DATE, MTLN.LOT_NUMBER, GBH.BATCH_NO,TAB.INVENTORY_ITEM_ID,
              MSI.SEGMENT1
           || '-'
           || MSI.SEGMENT2
           || '-'
           || MSI.SEGMENT3
           || '-'
           || MSI.SEGMENT4
           || '-'
           || MSI.SEGMENT5 ITEM_CODE,
           MSI.DESCRIPTION, TAB.LOT_NUMBER DETAIL_LOT_NUMBER, TAB.ACTUAL_QTY,
           TAB.TRANSACTION_UOM,
           DECODE (TAB.LINE_TYPE,
                     -1, 'INGREDIENTS',
                     1, 'PRODUCT',
                     2, 'BY-PRODUCT'
                    ) AS TYPE
       
      FROM GME_BATCH_HEADER GBH,
           GME_MATERIAL_DETAILS GBD,
           MTL_SYSTEM_ITEMS MSI,
           MTL_MATERIAL_TRANSACTIONS MTT,
           MTL_TRANSACTION_LOT_NUMBERS MTLN,
           (SELECT   A.BATCH_ID, B.INVENTORY_ITEM_ID, B.ORGANIZATION_ID,
                     A.ACTUAL_QTY, D.LOT_NUMBER, C.TRANSACTION_UOM, A.LINE_TYPE
                FROM GME_MATERIAL_DETAILS A,
                     MTL_SYSTEM_ITEMS B,
                     MTL_MATERIAL_TRANSACTIONS C,
                     MTL_TRANSACTION_LOT_NUMBERS D
               WHERE 1 = 1
                 AND A.MATERIAL_DETAIL_ID = C.TRX_SOURCE_LINE_ID
                 AND C.TRANSACTION_ID = D.TRANSACTION_ID
                 AND A.INVENTORY_ITEM_ID = B.INVENTORY_ITEM_ID
                 AND B.ORGANIZATION_ID = 89
                 AND A.ORGANIZATION_ID = :IO
                 --AND A.INVENTORY_ITEM_ID = :ITEM_ID
                 --AND A.BATCH_ID = GBH.BATCH_ID
            ORDER BY A.LINE_TYPE, A.LINE_NO, A.BATCH_ID) TAB
     WHERE 1 = 1
       AND MTT.TRANSACTION_ID = MTLN.TRANSACTION_ID
       AND GBD.MATERIAL_DETAIL_ID = MTT.TRX_SOURCE_LINE_ID
       AND GBH.BATCH_ID = GBD.BATCH_ID
       AND TAB.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
       AND TAB.ORGANIZATION_ID = MSI.ORGANIZATION_ID
       AND MSI.ORGANIZATION_ID = 89
       AND GBD.ORGANIZATION_ID = :IO
       AND GBD.BATCH_ID = TAB.BATCH_ID
       AND GBD.LINE_TYPE = 1
       AND GBD.LINE_NO = 1
       AND GBD.INVENTORY_ITEM_ID = :ITEM_ID
       AND TRUNC (GBH.ACTUAL_START_DATE)
                      BETWEEN TO_DATE (:TGL1, 'RRRR/MM/DD HH24:MI:SS') - 1
                          AND TO_DATE (:TGL2, 'RRRR/MM/DD HH24:MI:SS')
        --AND GBD.BATCH_ID = 578323 
) PP, YNP_TEST_ITEM_HISTORY YTIH

WHERE YTIH.INVENTORY_ITEM_ID = PP.INVENTORY_ITEM_ID
AND YTIH.LOT_NUMBER =  PP.LOT_NUMBER


=========================================================================
SELECT GBH.PLAN_CMPLT_DATE,
        NULL SHIFT,
        MTLN.LOT_NUMBER,
        GBH.BATCH_NO,
        MSI.SEGMENT1 ||'-'||MSI.SEGMENT2 ||'-'||MSI.SEGMENT3 ||'-'||MSI.SEGMENT4 ||'-'||MSI.SEGMENT5 ITEM_CODE,
        MSI.DESCRIPTION,
        TAB.LOT_NUMBER detail_LOT_NUMBER,
        TAB.ACTUAL_QTY,
        TAB.TRANSACTION_UOM,
        (
            SELECT YIH.TANGGAL_KIRIM
            FROM YNP_ITEMLOT_HISTORY YIH
            WHERE YIH.INVENTORY_ITEM_ID = :ITEM_ID
            AND YIH.LOT_NUMBER = TAB.LOT_NUMBER
            AND ROWNUM = 1
        ) TANGGAL_KIRIM,
        (
            SELECT YIH.QTY_KIRIM
            FROM YNP_ITEMLOT_HISTORY YIH
            WHERE YIH.INVENTORY_ITEM_ID = :ITEM_ID
            AND YIH.LOT_NUMBER = TAB.LOT_NUMBER
            AND ROWNUM = 1
        ) QTY_KIRIM,
        (
            SELECT YIH.DO_NUMBER
            FROM YNP_ITEMLOT_HISTORY YIH
            WHERE YIH.INVENTORY_ITEM_ID = :ITEM_ID
            AND YIH.LOT_NUMBER = TAB.LOT_NUMBER
            AND ROWNUM = 1
        ) DO_NUMBER,
        (
            SELECT YIH.NAMA_CUSTOMER
            FROM YNP_ITEMLOT_HISTORY YIH
            WHERE YIH.INVENTORY_ITEM_ID = :ITEM_ID
            AND YIH.LOT_NUMBER = TAB.LOT_NUMBER
            AND ROWNUM = 1
        ) NAMA_CUSTOMER
        
        
        
FROM GME_BATCH_HEADER GBH, GME_MATERIAL_DETAILS GBD, MTL_SYSTEM_ITEMS MSI,
        MTL_MATERIAL_TRANSACTIONS MTT, MTL_TRANSACTION_LOT_NUMBERS MTLN,
        (
            SELECT A.BATCH_ID, B.INVENTORY_ITEM_ID, B.ORGANIZATION_ID, A.ACTUAL_QTY, D.LOT_NUMBER, C.TRANSACTION_UOM
            FROM GME_MATERIAL_DETAILS A, MTL_SYSTEM_ITEMS B,
                    MTL_MATERIAL_TRANSACTIONS C, MTL_TRANSACTION_LOT_NUMBERS D
            WHERE 1 = 1
            AND A.MATERIAL_DETAIL_ID = C.TRX_SOURCE_LINE_ID
            AND C.TRANSACTION_ID = D.TRANSACTION_ID
            AND A.INVENTORY_ITEM_ID = B.INVENTORY_ITEM_ID
            AND B.ORGANIZATION_ID = 89
            --AND A.BATCH_ID = 578323
            ORDER BY A.LINE_TYPE, A.LINE_NO
        ) TAB
WHERE 1 = 1
AND MTT.TRANSACTION_ID = MTLN.TRANSACTION_ID
AND GBD.MATERIAL_DETAIL_ID = MTT.TRX_SOURCE_LINE_ID
AND GBH.BATCH_ID = GBD.BATCH_ID
AND TAB.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
AND TAB.ORGANIZATION_ID = MSI.ORGANIZATION_ID
AND MSI.ORGANIZATION_ID = 89
AND GBD.BATCH_ID = TAB.BATCH_ID
AND GBD.LINE_TYPE = 1
AND GBD.LINE_NO = 1
AND GBD.INVENTORY_ITEM_ID =:ITEM_ID
AND GBD.ORGANIZATION_ID = :IO 
AND TRUNC (GBH.ACTUAL_START_DATE)
                      BETWEEN TO_DATE (:TGL1, 'RRRR/MM/DD HH24:MI:SS')
                          AND TO_DATE (:TGL2, 'RRRR/MM/DD HH24:MI:SS') 
--222152
--AND GBD.BATCH_ID = 578323 